--------------------------------------------------------
--  DDL for Sequences
--------------------------------------------------------

CREATE SEQUENCE "SEQ_COMPRAS" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE "SEQ_MATERIAIS" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE "SEQ_DESENHOS" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE "SEQ_STATUS" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE "SEQ_SOLICITANTES" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE "SEQ_FORNECEDORES" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE "SEQ_CONDICOES_FRETE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE "SEQ_ORDENS_SERVICO" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE "SEQ_PERFIS" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;

--------------------------------------------------------
--  DDL for Tables
--------------------------------------------------------

CREATE TABLE "COMPRAS" 
(
    "COM_ID" NUMBER(10,0),
    "COM_DT_PEDIDO" DATE,
    "COM_OS" NUMBER(10,0),
    "COM_DESENHO" NUMBER(10,0),
    "COM_MATERIAL" NUMBER(10,0),
    "COM_DESCRICAO_MATERIAL" VARCHAR2(100),
    "COM_QTD" NUMBER(10,0),
    "COM_PERFIL" NUMBER(10,0),
    "COM_DIAMETRO_INT" NUMBER(8,2),
    "COM_DIAMETRO_EXT" NUMBER(8,2),
    "COM_ESPESSURA" NUMBER(8,2),
    "COM_LARGURA" NUMBER(8,2),
    "COM_COMPRIMENTO" NUMBER(8,2),
    "COM_DT_PRAZO" DATE,
    "COM_STATUS" NUMBER(10,0),
    "COM_FORNECEDOR" NUMBER(10,0),
    "COM_DT_COMPRA_MATERIAL" DATE,
    "COM_FRETE" NUMBER(10,0),
    "COM_NFE" VARCHAR2(32),
    "COM_DT_CHEGADA_MATERIAL" DATE,
    "COM_INFO_ADICIONAIS" VARCHAR2(500)
);

CREATE TABLE "MATERIAIS" 
(
    "MAT_ID" NUMBER(10,0),
    "MAT_NOME" VARCHAR2(100)
);

CREATE TABLE "DESENHOS" 
(
    "DES_ID" NUMBER(10,0),
    "DES_NOME" VARCHAR2(100)
);

CREATE TABLE "STATUS" 
(
    "STA_ID" NUMBER(10,0),
    "STA_NOME" VARCHAR2(32)
);

CREATE TABLE "SOLICITANTES" 
(
    "SOL_ID" NUMBER(10,0),
    "SOL_NOME" VARCHAR2(100)
);

CREATE TABLE "FORNECEDORES" 
(
    "FOR_ID" NUMBER(10,0),
    "FOR_NOME" VARCHAR2(100)
);

CREATE TABLE "CONDICOES_FRETE" 
(
    "CON_FRE_ID" NUMBER(10,0),
    "CON_FRE_NOME" VARCHAR2(3)
);

CREATE TABLE "ORDENS_SERVICO" 
(
    "OS_ID" NUMBER(10,0),
    "OS_NUMERO" VARCHAR2(100),
    "OS_SOLICITANTE" NUMBER(10,0)
);

CREATE TABLE "PERFIS" 
(
    "PER_ID" NUMBER(10,0),
    "PER_NOME" VARCHAR2(100)
);

--------------------------------------------------------
--  DDL for Triggers
--------------------------------------------------------

CREATE OR REPLACE NONEDITIONABLE TRIGGER "TG_SEQ_COMPRAS" 
BEFORE INSERT ON "COMPRAS"
FOR EACH ROW
BEGIN
    :NEW.COM_ID := SEQ_COMPRAS.NEXTVAL;
END;
/
ALTER TRIGGER "TG_SEQ_COMPRAS" ENABLE;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "TG_SEQ_MATERIAIS" 
BEFORE INSERT ON "MATERIAIS"
FOR EACH ROW
BEGIN
    :NEW.MAT_ID := SEQ_MATERIAIS.NEXTVAL;
END;
/
ALTER TRIGGER "TG_SEQ_MATERIAIS" ENABLE;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "TG_SEQ_DESENHOS" 
BEFORE INSERT ON "DESENHOS"
FOR EACH ROW
BEGIN
    :NEW.DES_ID := SEQ_DESENHOS.NEXTVAL;
END;
/
ALTER TRIGGER "TG_SEQ_DESENHOS" ENABLE;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "TG_SEQ_STATUS" 
BEFORE INSERT ON "STATUS"
FOR EACH ROW
BEGIN
    :NEW.STA_ID := SEQ_STATUS.NEXTVAL;
END;
/
ALTER TRIGGER "TG_SEQ_STATUS" ENABLE;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "TG_SEQ_SOLICITANTES" 
BEFORE INSERT ON "SOLICITANTES"
FOR EACH ROW
BEGIN
    :NEW.SOL_ID := SEQ_SOLICITANTES.NEXTVAL;
END;
/
ALTER TRIGGER "TG_SEQ_SOLICITANTES" ENABLE;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "TG_SEQ_FORNECEDORES" 
BEFORE INSERT ON "FORNECEDORES"
FOR EACH ROW
BEGIN
    :NEW.FOR_ID := SEQ_FORNECEDORES.NEXTVAL;
END;
/
ALTER TRIGGER "TG_SEQ_FORNECEDORES" ENABLE;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "TG_SEQ_CONDICOES_FRETE" 
BEFORE INSERT ON "CONDICOES_FRETE"
FOR EACH ROW
BEGIN
    :NEW.CON_FRE_ID := SEQ_CONDICOES_FRETE.NEXTVAL;
END;
/
ALTER TRIGGER "TG_SEQ_CONDICOES_FRETE" ENABLE;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "TG_SEQ_ORDENS_SERVICO" 
BEFORE INSERT ON "ORDENS_SERVICO"
FOR EACH ROW
BEGIN
    :NEW.OS_ID := SEQ_ORDENS_SERVICO.NEXTVAL;
END;
/
ALTER TRIGGER "TG_SEQ_ORDENS_SERVICO" ENABLE;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "TG_SEQ_PERFIS" 
BEFORE INSERT ON "PERFIS"
FOR EACH ROW
BEGIN
    :NEW.PER_ID := SEQ_PERFIS.NEXTVAL;
END;
/
ALTER TRIGGER "TG_SEQ_PERFIS" ENABLE;

--------------------------------------------------------
--  Constraints for Tables
--------------------------------------------------------

ALTER TABLE "COMPRAS" MODIFY ("COM_ID" CONSTRAINT "CK_COM_NN_01" NOT NULL ENABLE);
ALTER TABLE "COMPRAS" MODIFY ("COM_DT_PEDIDO" CONSTRAINT "CK_COM_NN_02" NOT NULL ENABLE);
ALTER TABLE "COMPRAS" MODIFY ("COM_OS" CONSTRAINT "CK_COM_NN_03" NOT NULL ENABLE);
ALTER TABLE "COMPRAS" MODIFY ("COM_DESENHO" CONSTRAINT "CK_COM_NN_04" NOT NULL ENABLE);
ALTER TABLE "COMPRAS" MODIFY ("COM_MATERIAL" CONSTRAINT "CK_COM_NN_05" NOT NULL ENABLE);
ALTER TABLE "COMPRAS" MODIFY ("COM_QTD" CONSTRAINT "CK_COM_NN_06" NOT NULL ENABLE);
ALTER TABLE "COMPRAS" MODIFY ("COM_FORNECEDOR" CONSTRAINT "CK_COM_NN_07" NOT NULL ENABLE);
ALTER TABLE "COMPRAS" ADD CONSTRAINT "PK_COMPRAS" PRIMARY KEY ("COM_ID") USING INDEX ENABLE;

ALTER TABLE "MATERIAIS" MODIFY ("MAT_ID" CONSTRAINT "CK_MAT_NN_01" NOT NULL ENABLE);
ALTER TABLE "MATERIAIS" MODIFY ("MAT_NOME" CONSTRAINT "CK_MAT_NN_02" NOT NULL ENABLE);
ALTER TABLE "MATERIAIS" ADD CONSTRAINT "PK_MATERIAIS" PRIMARY KEY ("MAT_ID") USING INDEX ENABLE;

ALTER TABLE "DESENHOS" MODIFY ("DES_ID" CONSTRAINT "CK_DES_NN_01" NOT NULL ENABLE);
ALTER TABLE "DESENHOS" MODIFY ("DES_NOME" CONSTRAINT "CK_DES_NN_02" NOT NULL ENABLE);
ALTER TABLE "DESENHOS" ADD CONSTRAINT "PK_DESENHOS" PRIMARY KEY ("DES_ID") USING INDEX ENABLE;

ALTER TABLE "STATUS" MODIFY ("STA_ID" CONSTRAINT "CK_STA_NN_01" NOT NULL ENABLE);
ALTER TABLE "STATUS" MODIFY ("STA_NOME" CONSTRAINT "CK_STA_NN_02" NOT NULL ENABLE);
ALTER TABLE "STATUS" ADD CONSTRAINT "PK_STATUS" PRIMARY KEY ("STA_ID") USING INDEX ENABLE;

ALTER TABLE "SOLICITANTES" MODIFY ("SOL_ID" CONSTRAINT "CK_SOL_NN_01" NOT NULL ENABLE);
ALTER TABLE "SOLICITANTES" MODIFY ("SOL_NOME" CONSTRAINT "CK_SOL_NN_02" NOT NULL ENABLE);
ALTER TABLE "SOLICITANTES" ADD CONSTRAINT "PK_SOLICITANTES" PRIMARY KEY ("SOL_ID") USING INDEX ENABLE;

ALTER TABLE "FORNECEDORES" MODIFY ("FOR_ID" CONSTRAINT "CK_FOR_NN_01" NOT NULL ENABLE);
ALTER TABLE "FORNECEDORES" MODIFY ("FOR_NOME" CONSTRAINT "CK_FOR_NN_02" NOT NULL ENABLE);
ALTER TABLE "FORNECEDORES" ADD CONSTRAINT "PK_FORNECEDORES" PRIMARY KEY ("FOR_ID") USING INDEX ENABLE;

ALTER TABLE "CONDICOES_FRETE" MODIFY ("CON_FRE_ID" CONSTRAINT "CK_CFR_NN_01" NOT NULL ENABLE);
ALTER TABLE "CONDICOES_FRETE" MODIFY ("CON_FRE_NOME" CONSTRAINT "CK_CFR_NN_02" NOT NULL ENABLE);
ALTER TABLE "CONDICOES_FRETE" ADD CONSTRAINT "PK_CONDICOES_FRETE" PRIMARY KEY ("CON_FRE_ID") USING INDEX ENABLE;

ALTER TABLE "ORDENS_SERVICO" MODIFY ("OS_ID" CONSTRAINT "CK_OS_NN_01" NOT NULL ENABLE);
ALTER TABLE "ORDENS_SERVICO" MODIFY ("OS_NUMERO" CONSTRAINT "CK_OS_NN_02" NOT NULL ENABLE);
ALTER TABLE "ORDENS_SERVICO" MODIFY ("OS_SOLICITANTE" CONSTRAINT "CK_OS_NN_03" NOT NULL ENABLE);
ALTER TABLE "ORDENS_SERVICO" ADD CONSTRAINT "PK_ORDENS_SERVICO" PRIMARY KEY ("OS_ID") USING INDEX ENABLE;

ALTER TABLE "PERFIS" MODIFY ("PER_ID" CONSTRAINT "CK_PER_NN_01" NOT NULL ENABLE);
ALTER TABLE "PERFIS" MODIFY ("PER_NOME" CONSTRAINT "CK_PER_NN_02" NOT NULL ENABLE);
ALTER TABLE "PERFIS" ADD CONSTRAINT "PK_PERFIS" PRIMARY KEY ("PER_ID") USING INDEX ENABLE;

--------------------------------------------------------
--  Ref Constraints for Tables
--------------------------------------------------------

ALTER TABLE "COMPRAS" ADD CONSTRAINT "FK_COM_DESENHO" FOREIGN KEY ("COM_DESENHO") REFERENCES "DESENHOS" ("DES_ID") ENABLE;
ALTER TABLE "COMPRAS" ADD CONSTRAINT "FK_COM_FORNECEDOR" FOREIGN KEY ("COM_FORNECEDOR") REFERENCES "FORNECEDORES" ("FOR_ID") ENABLE;
ALTER TABLE "COMPRAS" ADD CONSTRAINT "FK_COM_PERFIL" FOREIGN KEY ("COM_PERFIL") REFERENCES "PERFIS" ("PER_ID") ENABLE;
ALTER TABLE "COMPRAS" ADD CONSTRAINT "FK_COM_FRETE" FOREIGN KEY ("COM_FRETE") REFERENCES "CONDICOES_FRETE" ("CON_FRE_ID") ENABLE;
ALTER TABLE "COMPRAS" ADD CONSTRAINT "FK_COM_STATUS" FOREIGN KEY ("COM_STATUS") REFERENCES "STATUS" ("STA_ID") ENABLE;
ALTER TABLE "COMPRAS" ADD CONSTRAINT "FK_COM_MATERIAL" FOREIGN KEY ("COM_MATERIAL") REFERENCES "MATERIAIS" ("MAT_ID") ENABLE;
ALTER TABLE "COMPRAS" ADD CONSTRAINT "FK_COM_OS" FOREIGN KEY ("COM_OS") REFERENCES "ORDENS_SERVICO" ("OS_ID") ENABLE;

ALTER TABLE "ORDENS_SERVICO" ADD CONSTRAINT "FK_OS_SOLICITANTE" FOREIGN KEY ("OS_SOLICITANTE") REFERENCES "SOLICITANTES" ("SOL_ID") ENABLE;